apiVersion: v1
kind: ConfigMap
metadata:
  name: capstone-config
data:
  config.json: |
    {
      "VITE_API_BASE_URL": "http://54.198.143.174:30017"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deploy
  labels:
    app: capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone-ctr
          image: rootovertwo/capstone-project-frontend:latest
          ports:
            - containerPort: 5173
          volumeMounts:
            - name: frontend-config
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
          imagePullPolicy: Always
      volumes:
        - name: frontend-config
          configMap:
            name: capstone-config
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-service
spec:
  selector:
    app: capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 30007
  type: NodePort
